### ISSUE TITLE
ThemeColor.TEAL is not teal

### ISSUE THREAD

**Issue by gnawf** [garretyoder/Colorful#11]
Broken by commit 1b8f015

Issue: The [styles](https://github.com/garretyoder/Colorful/blob/1b8f015f21b745ae23e40be596179dc4186d0ca5/library/src/main/res/values/styles.xml#L74-L86) `primary7` and `primary8` are exactly the same, but `primary8` should be teal instead of cyan. The same applies for `accent8`. The ordinal value of [ThemeColor.TEAL](https://github.com/garretyoder/Colorful/blob/1b8f015f21b745ae23e40be596179dc4186d0ca5/library/src/main/java/org/polaric/colorful/Colorful.java#L85) is 8.

**Comment by garretyoder** [comment]
Whoops, was bound to foul something up with copy/pasting. Fixed in 8f7c5ce
