### ISSUE TITLE
make the public class ColorPickerDialog extends android.support.v7.app.AlertDialog is better than just extends Dialog

### ISSUE THREAD

**Issue by a1265137718** [garretyoder/Colorful#15]
make the public class ColorPickerDialog extends android.support.v7.app.AlertDialog is better than just extends Dialog ,in this way ,There will be no white blank title bar

**Comment by garretyoder** [comment]
How are you using it? In every scenario I've used it in, there is no blank title bar.

**Comment by a1265137718** [comment]
i run the app in my mobile MEIZU note2 flyme6.0 os   , i have create a button , when click it, the dialog will show .The style of the dialog box from top to bottom is white -> the current theme color-> can be selected for all theme colors
