### ISSUE TITLE
why no appbar when mainActivity extends CActivity 

### ISSUE THREAD

**Issue by Krosxx** [garretyoder/Colorful#19]
this has no appbar when mainActivity extends CActivity

**Comment by Krosxx** [comment]
v 1.1

**Comment by kksingla** [comment]
Colorful.config(this).accentColor(Colorful.ThemeColor.AMBER).primaryColor(Colorful.ThemeColor.CYAN).apply();
        Colorful.applyTheme(this,false);

**Comment by garretyoder** [comment]
Extending CActivity will override the base theme that activity is using. Colorful does not include a app bar in it's theme, meaning you'll simply have to add a toolbar yourself in your xml layout.
