### ISSUE TITLE
What is the use of "override" and "appcompat"?

### ISSUE THREAD

**Issue by tcqq** [garretyoder/Colorful#21]
Hi, thankyou your library, I'm useing 2.0 version now, I want know what is the use of `override` and `appcompat`?

`ColorfulKt.Colorful().apply(activity, override, appcompat);`

When should I use true and when should I use false?

**Comment by tcqq** [comment]
`isDark` is `true` now, but the theme show is not dark, What did i do wrong? How should I correct it?

Appliacation: 
`
            Defaults defaults = new Defaults(
                    ThemeColor.DEEP_PURPLE,
                    ThemeColor.PINK,
                    false,
                    true,
                    0);
`

Activity:
`ColorfulKt.Colorful().apply(this, true, false);`

**Comment by garretyoder** [comment]
This is explained in the readme.

The override value will control whether Colorful overrides your activitie's existing base theme, or merely sets primary and accent colors. Note: dark/light themeing will not work when override is disabled

**Comment by tcqq** [comment]
Ok, thanks.
