### ISSUE TITLE
Support colorPrimaryDark (and maybe more)

### ISSUE THREAD

**Issue by MFlisar** [garretyoder/Colorful#24]
At least to be able to set the `colorPrimaryDark` as well through Colorful would be very nice.

Additional text colors would be nice as well altough it's not that important...

**Comment by MFlisar** [comment]
Just found out that this is supported and hidden in the `ColorPack` class

**Comment by garretyoder** [comment]
This is something I forgot to add in the readme, feel free to open a PR to add it to the readme.
