### ISSUE TITLE
Usage in custom activity

### ISSUE THREAD

**Issue by MFlisar** [garretyoder/Colorful#25]
In a custom activity I have to call ` Colorful().apply(this, override = true, appcompat = false)` in `onCreate`. I'm missing the delegate for the `onResume` call like the example here has it:  https://github.com/garretyoder/Colorful/blob/master/library/src/main/java/io/multimoon/colorful/CAppCompatActivity.kt

This is necessary in a custom activity as well, isn't it?

**Comment by garretyoder** [comment]
There's a Colorful().hasChanged() method slated for 2.1 that will resolve this issue. 2.1 is scheduled for release this weekend.
