### ISSUE TITLE
Support dynamic configs

### ISSUE THREAD

**Issue by MFlisar** [garretyoder/Colorful#26]
Instead of always loading the saved preferences, could you add support for a dynamic config?

E.g. I would like to pass in a custom `Defaults` to `Colorful().apply(this, override = true, appcompat = false)` which should be used instead of the saved one if present

**Comment by garretyoder** [comment]
Could you be a bit more specific? Defaults is just a object Colorful reads it's default settings from.

**Comment by MFlisar** [comment]
I thought I would like to be able to use a custom object instead the one read from preferences, now I know I don't need this. I use different basic themes to solve this.

The idea was to create a `Defaults` object and use it (no preference persistence, no overriding by already persisted settings read from preference) as an option to create custom themes.
