### ISSUE TITLE
Request to add color

### ISSUE THREAD

**Issue by tcqq** [garretyoder/Colorful#34]
@garretyoder Request to add `DARK_GREY`, because use "DARK_GREY" color in dark theme is best choose, thanks.
![image](https://user-images.githubusercontent.com/10644057/39468387-531640f0-4d65-11e8-91e7-2ccc7cd9617f.png)
![image](https://user-images.githubusercontent.com/10644057/39468560-2f555a92-4d66-11e8-93b0-1709af092686.png)
![image](https://user-images.githubusercontent.com/10644057/39468529-045f2912-4d66-11e8-958c-e365452146f8.png)

**Comment by garretyoder** [comment]
I will not be adding any further colors simply because I have chosen to adhere to the [material color pallet](https://material.io/guidelines/style/color.html#color-color-palette)

However, thanks to a helpful commit(#29) you can now define your own custom colors and mix them with Colorful's defaults. See the readme on how to accomplish this.

**Comment by tcqq** [comment]
@garretyoder Thanks:), but I found a problem, I set `colorPrimaryDark` to red, but it not work.
![image](https://user-images.githubusercontent.com/10644057/39509280-46592d42-4e18-11e8-9e7b-ed2ef76860bd.png)

 If this value is `accentColor`, it also not work.

```
ThemeColorInterface themeColor = new CustomThemeColor(
    getContext(),
    R.style.dark_grey_primary_color,
    R.style.dark_grey_primary_dark_color,
    R.color.dark_gray,
    R.color.red);
```
```
Colorful().edit()
    .setPrimaryColor(themeColor)
    .apply(getContext(), () -> {
      recreate();
      return null;
})).isDisposed();
```
```
    <style name="dark_grey_primary_color">
        <item name="colorPrimary">@color/dark_gray</item>
    </style>
    <style name="dark_grey_primary_dark_color">
        <item name="colorPrimaryDark">@color/red</item>
    </style>
```

**Comment by tcqq** [comment]
I am using this method to set `colorPrimaryDark` now.
```
ThemeColorInterface themeColor = new CustomThemeColor(
    getContext(),
    R.style.dark_grey_primary_color,
    0,
    R.color.dark_gray,
    R.color.red);
```

```
    <style name="dark_grey_primary_color">
        <item name="colorPrimary">@color/dark_gray</item>
        <item name="colorPrimaryDark">@color/red</item>
    </style>
```
