### ISSUE TITLE
Sample code for use without kotlin

### ISSUE THREAD

**Issue by bmbariah** [garretyoder/Colorful#38]
Is is possible to use this without having to use kotlin? just Java
Kindly share some sample code on the README.
I tried some Kotlin decompiling but it didn't work

**Comment by garretyoder** [comment]
This will compile work and function in a java project perfectly fine, infact the API will be the same, you just won't have access to optional arguments is all. If you're having issue with a specific api endpoint in Java, then I'd be happy to help.

**Comment by bmbariah** [comment]
For starters, I'm using this on my root Application class for initialization
`Defaults defaults = new Defaults(
                ThemeColor.BLUE,
                ThemeColor.YELLOW,
                true,
                true,
                0);
        initColorful(this, defaults);`

but can't figure out what code to use to actually change color in my Activity color. Kindly assist

**Comment by garretyoder** [comment]
Read up on the wiki, it goes over how to do this. The api in Java is almost identical. Kotlin is a JVM language. you need to call `initColorful`.

Setting colors at runtime is also covered in the wiki.

```
Colorful().edit()
        .setPrimaryColor(ThemeColor.RED)
        .setAccentColor(ThemeColor.BLUE)
        .setDarkTheme(true)
        .setTranslucent(true)
        .apply(context:Context)
```
The only difference in java will be the ending `;`.

**Comment by bmbariah** [comment]
Thanks. The callback was giving me errors so i  set it to null.

**Comment by Naguchennai** [comment]
how you fixed that callback problem?
