### ISSUE TITLE
Material Drawer Theming Support?

### ISSUE THREAD

**Issue by shripal17** [garretyoder/Colorful#41]
This is the best theming library i have found so far!

I hope you add support for [Mike Penz's Material Drawer Library](https://github.com/mikepenz/MaterialDrawer) (also [MaterialDrawerKt](https://github.com/zsmb13/MaterialDrawerKt) which is based on the original Library) 

I tried using the Colorful's 
```kotlin
                .setCustomThemeOverride(R.style.AppTheme)
``` 
with the theme attributes specified [here](https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml)
but it doesnt seem to work or maybe I'm doing it wrong?

**Comment by garretyoder** [comment]
What exactly isn't working? At it's core, colorful is very simple. It uses Android's native style engine, just as if you set a style in xml. How different libraries react and use the Android styles is up to them, not colorful.

**Comment by shripal17** [comment]
Specifically, the dark theme doesn't get applied to the navigation drawer built dynamically by the above mentioned library. 
Thanks

**Comment by garretyoder** [comment]
If you set a custom theme, or disable theme overriding you will disable dark theme functionality, please see the wiki for more info on this.

Other than that, the library you're using not respecting the Android style isn't a colorful issue, you would run into the same issue with or without colorful. Colorful uses Android's style engine and just provides more features to it.

Closing as this is a issue unrelated to colorful. If you have any further questions please open another ticket.
