### ISSUE TITLE
Realtime accent color change ?

### ISSUE THREAD

**Issue by bmbariah** [garretyoder/Colorful#8]
Can we have the accent colors change immediately after apply? That is without leaving the current screen? I tried to trigger a color change from color picker dialog but it doesn't do anything to the current screen

**Comment by meierjan** [comment]
I don't think this is possible without extra implemetations of change events/callback. If you change the theme you even have to restart the activity if I have the source code correctly  in mind.

**Comment by bmbariah** [comment]
Thanks, turns out Themes are immutable and have to be per-declared and can't be changed on the go to the millions of the colors available

**Comment by garretyoder** [comment]
Apologies on the late reply, but this is indeed actually possible. I've implemented the same thing in my own App, Cluttr. Feel free to check it out & see how I implemented it.

**Comment by bmbariah** [comment]
Looks great, how did you achieve this? Are you reloading the entire activity?
